notifications:
  email:
    - travis-ci@pimcore.org

sudo: required
language: php

php:
  - 5.6.29
  - 7
  - 7.1

addons:
  hosts:
    - pimcore-test.dev

install:
  - chmod +x .travis/setup-sudo.sh && .travis/setup-sudo.sh
  - composer install

script:
  - (cd tests && chmod +x alltests.sh && ./alltests.sh)

after_script:
  - cat $TRAVIS_BUILD_DIR/tests/tmp/var/log/debug.log
  - cat $TRAVIS_BUILD_DIR/tests/tmp/var/log/php.log
  - cat $TRAVIS_BUILD_DIR/apache-error.log
  - cat $TRAVIS_BUILD_DIR/apache-access.log
